#!/bin/bash

pyfile=$PYFILE

if [ -z "$pyfile" ]; then
  echo "Error: PYFILE environment variable not set"
else
  python -m py_compile "$pyfile"
  if [ $? -eq 0 ]; then
    echo "Compiled $pyfile to ${pyfile}c"
  else
    echo "Error compiling $pyfile"
  fi
fi
